Maestro\CoreBundle\Entity\CostoInsumo:
    type: entity
    table: costo_insumo
    indexes:
        IDX_A445C636CE208F97:
            columns:
                - insumo_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        fechaCostoInsumo:
            type: datetime
            nullable: false
            column: fecha_costo_insumo
        costoInsumo:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: costo_insumo
    manyToOne:
        insumo:
            targetEntity: CtlInsumo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                insumo_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
