Maestro\CoreBundle\Entity\CtlDepartamento:
    type: entity
    table: ctl_departamento
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Identificador codigo catálogo maestro para cada departamento'
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: 'Descripción nombre del departamento'
        codigoCnr:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: 'Código CNR para departamento'
            column: codigo_cnr
        abreviatura:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: 'Abreviatura departamento'
        idEstablecimientoRegion:
            type: integer
            nullable: true
            unsigned: false
            comment: 'Identificador a la que pertenece el departamento según regiones administrativas del Ministerio de Salud'
            column: id_establecimiento_region
        idPais:
            type: integer
            nullable: true
            unsigned: false
            comment: 'Identificador código del país al que pertenece el departamento'
            column: id_pais
        idUsuarioReg:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: 'Auditoría usuario ingreso el registro'
            column: id_usuario_reg
        fechaHoraReg:
            type: datetime
            nullable: true
            comment: 'Auditoría fecha y hora ingreso de registro'
            column: fecha_hora_reg
        idUsuarioMod:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: 'Auditoría usuario modificó el registro'
            column: id_usuario_mod
        fechaHoraMod:
            type: datetime
            nullable: true
            comment: 'Auditoría fecha y hora modificación del registro'
            column: fecha_hora_mod
        iso31662:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: 'Código de departamento según norma ISO 3166-2 '
    lifecycleCallbacks: {  }
