Maestro\CoreBundle\Entity\CtlInsumo:
    type: entity
    table: ctl_insumo
    indexes:
        IDX_9DB3222BD744E62:
            columns:
                - ctl_presentacionid
        IDX_9DB322272F1374E:
            columns:
                - grupoid
        IDX_9DB3222D2D8661B:
            columns:
                - ctl_unidad_medidaid
        IDX_9DB32221F3126F0:
            columns:
                - ctl_productoid
        IDX_9DB3222DD0A3533:
            columns:
                - ctl_nivel_usoid
        IDX_9DB32227A93ADB3:
            columns:
                - ctl_forma_farmaceutica_id
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codigoNu:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: codigo_nu
        ctlProgramaid:
            type: integer
            nullable: true
            unsigned: false
            column: ctl_programaid
        codigoSinab:
            type: string
            nullable: false
            length: 10
            fixed: false
            column: codigo_sinab
        codificacionInsumo:
            type: bigint
            nullable: false
            unsigned: false
            default: '0'
            column: codificacion_insumo
        codigoSinabExt:
            type: bigint
            nullable: false
            unsigned: false
            default: '0'
            column: codigo_sinab_ext
        listadoOficial:
            type: boolean
            nullable: false
            default: false
            column: listado_oficial
        nombreLargoInsumo:
            type: text
            nullable: false
            length: null
            fixed: false
            column: nombre_largo_insumo
        registroSchema:
            type: datetime
            nullable: true
            default: '(now())::timestamp(0) without time zone'
            column: registro_schema
        detalleSchema:
            type: text
            nullable: true
            length: null
            fixed: false
            default: 'Agregado antes de gestor de maestros'
            column: detalle_schema
        userIdSchema:
            type: bigint
            nullable: true
            unsigned: false
            default: '1'
            column: user_id_schema
        ipUserSchema:
            type: string
            nullable: true
            length: null
            fixed: false
            default: 0.0.0.0
            column: ip_user_schema
        estadoSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: estado_schema
        enableSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: enable_schema
        detalleInsumo:
            type: text
            nullable: true
            length: null
            fixed: false
            default: na
            column: detalle_insumo
        venInsumo:
            type: smallint
            nullable: true
            unsigned: false
            comment: 'Vital, Escencial, No escencial'
            column: ven_insumo
        costoInsumo:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: 'Costo del ultimo valor resgistrado'
            column: costo_insumo
        procesadoInsumo:
            type: boolean
            nullable: false
            default: false
            column: procesado_insumo
    manyToOne:
        ctlPresentacionid:
            targetEntity: CtlPresentacion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_presentacionid:
                    referencedColumnName: id
            orphanRemoval: false
        grupoid:
            targetEntity: CtlGrupo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                grupoid:
                    referencedColumnName: id
            orphanRemoval: false
        ctlUnidadMedidaid:
            targetEntity: CtlUnidadMedida
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_unidad_medidaid:
                    referencedColumnName: id
            orphanRemoval: false
        ctlProductoid:
            targetEntity: CtlProducto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_productoid:
                    referencedColumnName: id
            orphanRemoval: false
        ctlNivelUsoid:
            targetEntity: CtlNivelUso
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_nivel_usoid:
                    referencedColumnName: id
            orphanRemoval: false
        ctlFormaFarmaceutica:
            targetEntity: CtlFormaFarmaceutica
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_forma_farmaceutica_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        ctlConcentracionid:
            targetEntity: CtlConcentracion
            cascade: {  }
            mappedBy: null
            inversedBy: ctlInsumoid
            joinTable:
                name: insumo_concentracion
                joinColumns:
                    -
                        name: ctl_insumoid
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: ctl_concentracionid
                        referencedColumnName: id
            orderBy: null
        ctlFormaFarmaceuticaid:
            targetEntity: CtlFormaFarmaceutica
            cascade: {  }
            mappedBy: ctlInsumoid
            inversedBy: null
            joinTable: null
            orderBy: null
        ctlPrinicipio:
            targetEntity: CtlPrincipio
            cascade: {  }
            mappedBy: null
            inversedBy: ctlInsumo
            joinTable:
                name: insumo_principio
                joinColumns:
                    -
                        name: ctl_insumo
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: ctl_prinicipio
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
