Maestro\CoreBundle\Entity\CtlMunicipio:
    type: entity
    table: ctl_municipio
    indexes:
        IDX_914172ED6325E299:
            columns:
                - id_departamento
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Identificador código de municipio'
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: 'Descripción nombre del Municipio'
        codigoCnr:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: 'Identificador Código de Municipio según CNR'
            column: codigo_cnr
        abreviatura:
            type: string
            nullable: true
            length: 60
            fixed: false
            comment: 'Abreviatura de Municipio'
        idUsuarioReg:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: 'Auditoría usuario ingreso el registro'
            column: id_usuario_reg
        fechaHoraReg:
            type: datetime
            nullable: true
            comment: 'Auditoría fecha y hora ingreso de registro'
            column: fecha_hora_reg
        idUsuarioMod:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: 'Auditoría usuario modificó el registro'
            column: id_usuario_mod
        fechaHoraMod:
            type: datetime
            nullable: true
            comment: 'Auditoría fecha y hora modificación del registro'
            column: fecha_hora_mod
        cabecera:
            type: boolean
            nullable: false
            comment: 'Identificador para determinar si se incluyen o no las cabeceras departamentales'
    manyToOne:
        idDepartamento:
            targetEntity: CtlDepartamento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_departamento:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
