Maestro\CoreBundle\Entity\CtlNivelUso:
    type: entity
    table: ctl_nivel_uso
    uniqueConstraints:
        ctl_nivel_uso_nombre_nivel_uso_key:
            columns:
                - nombre_nivel_uso
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombreNivelUso:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: nombre_nivel_uso
        detalleNivelUso:
            type: string
            nullable: true
            length: 255
            fixed: false
            default: ''
            column: detalle_nivel_uso
        registroSchema:
            type: datetime
            nullable: true
            default: '2017-02-26 21:24:50.81923'
            column: registro_schema
        detalleSchema:
            type: text
            nullable: true
            length: null
            fixed: false
            default: 'Agregado antes de gestor de maestros'
            column: detalle_schema
        userIdSchema:
            type: bigint
            nullable: true
            unsigned: false
            default: '(1)::bigint'
            column: user_id_schema
        ipUserSchema:
            type: string
            nullable: true
            length: null
            fixed: false
            default: 0.0.0.0
            column: ip_user_schema
        estadoSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: estado_schema
        enableSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: enable_schema
    lifecycleCallbacks: {  }
