Maestro\CoreBundle\Entity\CtlPrograma:
    type: entity
    table: ctl_programa
    indexes:
        IDX_6B00F8DBFD8A7328:
            columns:
                - programa_id
    uniqueConstraints:
        ctl_programa_nombre_programa_key:
            columns:
                - nombre_programa
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombrePrograma:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: nombre_programa
        detallePrograma:
            type: text
            nullable: true
            length: null
            fixed: false
            column: detalle_programa
        registroSchema:
            type: datetime
            nullable: true
            default: '2017-02-26 21:27:44.60444'
            column: registro_schema
        detalleSchema:
            type: text
            nullable: true
            length: null
            fixed: false
            default: 'Agregado antes de gestor de maestros'
            column: detalle_schema
        userIdSchema:
            type: bigint
            nullable: true
            unsigned: false
            default: '(1)::bigint'
            column: user_id_schema
        ipUserSchema:
            type: string
            nullable: true
            length: null
            fixed: false
            default: 0.0.0.0
            column: ip_user_schema
        estadoSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: estado_schema
        enableSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: enable_schema
    manyToOne:
        programa:
            targetEntity: CtlPrograma
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                programa_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
