Maestro\CoreBundle\Entity\CtlRol:
    type: entity
    table: ctl_rol
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombreRol:
            type: string
            nullable: false
            length: 50
            fixed: false
            column: nombre_rol
    manyToMany:
        acceso:
            targetEntity: CtlAcceso
            cascade: {  }
            mappedBy: rol
            inversedBy: null
            joinTable: null
            orderBy: null
        ctlAcceso:
            targetEntity: CtlAcceso
            cascade: {  }
            mappedBy: null
            inversedBy: ctlRole
            joinTable:
                name: role_acceso
                joinColumns:
                    -
                        name: ctl_role_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: ctl_acceso_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
