Maestro\CoreBundle\Entity\Syslog:
    type: entity
    table: syslog
    indexes:
        IDX_C142E2D77D699553:
            columns:
                - ctl_log_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        registroLog:
            type: datetime
            nullable: false
            default: '(now())::timestamp(0) without time zone'
            column: registro_log
        descripcionLog:
            type: text
            nullable: true
            length: null
            fixed: false
            column: descripcion_log
    manyToOne:
        ctlLog:
            targetEntity: CtlLog
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_log_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
