Minsal\SuministroBundle\Entity\CtlSuministro:
    type: entity
    table: ctl_suministro
    indexes:
        IDX_23741A446EB0AB02:
            columns:
                - rol_valida_suministro
        IDX_23741A44D64E375F:
            columns:
                - ctl_suministroid
        IDX_23741A44DF5CB336:
            columns:
                - rol_solicita_suministro
        IDX_23741A44A9C99084:
            columns:
                - codificacion_suministro
    uniqueConstraints:
        ctl_suministro_nombre_suministro_key:
            columns:
                - nombre_suministro
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombreSuministro:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: nombre_suministro
        detalleSuministro:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: detalle_suministro
        registroSchema:
            type: datetime
            nullable: true
            default: '2017-02-26 21:29:15.600166'
            column: registro_schema
        detalleSchema:
            type: text
            nullable: true
            length: null
            fixed: false
            default: 'Agregado antes de gestor de maestros'
            column: detalle_schema
        userIdSchema:
            type: bigint
            nullable: true
            unsigned: false
            default: '(1)::bigint'
            column: user_id_schema
        userIpSchema:
            type: string
            nullable: true
            length: null
            fixed: false
            default: 0.0.0.0
            column: user_ip_schema
        estadoSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: estado_schema
        enableSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: enable_schema
        codigoSuministro:
            type: string
            nullable: false
            length: 2
            fixed: false
            default: '00'
            column: codigo_suministro
    manyToOne:
        rolValidaSuministro:
            targetEntity: CtlRol
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rol_valida_suministro:
                    referencedColumnName: id
            orphanRemoval: false
        ctlSuministroid:
            targetEntity: CtlSuministro
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_suministroid:
                    referencedColumnName: id
            orphanRemoval: false
        rolSolicitaSuministro:
            targetEntity: CtlRol
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rol_solicita_suministro:
                    referencedColumnName: id
            orphanRemoval: false
        codificacionSuministro:
            targetEntity: CtlCodificacion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                codificacion_suministro:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        unidadMedida:
            targetEntity: CtlUnidadMedida
            cascade: {  }
            mappedBy: null
            inversedBy: suministro
            joinTable:
                name: suministro_unidad_medida
                joinColumns:
                    -
                        name: suministro_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: unidad_medida_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
