Minsal\SuministroBundle\Entity\CtlViaAdministracion:
    type: entity
    table: ctl_via_administracion
    uniqueConstraints:
        un_via_administracion:
            columns:
                - nombre_via_administracion
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombreViaAdministracion:
            type: text
            nullable: false
            length: null
            fixed: false
            column: nombre_via_administracion
        detalleViaAdministracion:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: detalle_via_administracion
        registroSchema:
            type: datetime
            nullable: true
            default: '(now())::timestamp(0) without time zone'
            column: registro_schema
        detalleSchema:
            type: text
            nullable: true
            length: null
            fixed: false
            default: 'Agregado antes de gestor de maestros'
            column: detalle_schema
        userIdSchema:
            type: bigint
            nullable: true
            unsigned: false
            default: '1'
            column: user_id_schema
        userIpSchema:
            type: string
            nullable: true
            length: null
            fixed: false
            default: 0.0.0.0
            column: user_ip_schema
        estadoSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: estado_schema
        enableSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: enable_schema
    lifecycleCallbacks: {  }
