Minsal\SuministroBundle\Entity\MntAlternativo:
    type: entity
    table: mnt_alternativo
    indexes:
        fki_alternativo_user_schema:
            columns:
                - user_id_schema
        IDX_9FAA38C63FC97345:
            columns:
                - ctl_insumo_alternativo
        IDX_9FAA38C69DB3222:
            columns:
                - ctl_insumo
    uniqueConstraints:
        unique_mezcla:
            columns:
                - ctl_insumo
                - ctl_insumo_alternativo
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        multiploAlternativo:
            type: bigint
            nullable: false
            unsigned: false
            column: multiplo_alternativo
        registroSchema:
            type: datetime
            nullable: true
            default: '(now())::timestamp(0) without time zone'
            column: registro_schema
        detalleSchema:
            type: text
            nullable: true
            length: null
            fixed: false
            default: 'Agregado antes de gestor de maestros'
            column: detalle_schema
        userIpSchema:
            type: string
            nullable: true
            length: null
            fixed: false
            default: 0.0.0.0
            column: user_ip_schema
        estadoSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: estado_schema
        enableSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: enable_schema
    manyToOne:
        ctlInsumoAlternativo:
            targetEntity: MntInsumo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_insumo_alternativo:
                    referencedColumnName: id
            orphanRemoval: false
        ctlInsumo:
            targetEntity: MntInsumo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_insumo:
                    referencedColumnName: id
            orphanRemoval: false
        userSchema:
            targetEntity: FosUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id_schema:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
