Minsal\SuministroBundle\Entity\SegAcceso:
    type: entity
    table: seg_acceso
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombreAcceso:
            type: string
            nullable: false
            length: 250
            fixed: false
            column: nombre_acceso
        pathAcceso:
            type: string
            nullable: false
            length: 250
            fixed: false
            column: path_acceso
        publicAcceso:
            type: boolean
            nullable: false
            default: false
            column: public_acceso
        accesoId:
            type: bigint
            nullable: true
            unsigned: false
            column: acceso_id
        ordenAcceso:
            type: integer
            nullable: false
            unsigned: false
            default: '1'
            column: orden_acceso
        visibleAcceso:
            type: boolean
            nullable: false
            default: false
            column: visible_acceso
    manyToMany:
        rol:
            targetEntity: CtlRol
            cascade: {  }
            mappedBy: null
            inversedBy: acceso
            joinTable:
                name: seg_permisos
                joinColumns:
                    -
                        name: acceso_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: rol_id
                        referencedColumnName: id
            orderBy: null
        ctlRole:
            targetEntity: CtlRol
            cascade: {  }
            mappedBy: ctlAcceso
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
