acceso_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:CtlAcceso:index" }
    methods:  GET

acceso_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:CtlAcceso:show" }
    methods:  GET

acceso_new:
    path:     /new
    defaults: { _controller: "MaestroModeloBundle:CtlAcceso:new" }
    methods:  [GET, POST]

acceso_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaestroModeloBundle:CtlAcceso:edit" }
    methods:  [GET, POST]

acceso_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaestroModeloBundle:CtlAcceso:delete" }
    methods:  DELETE
