alternativo_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:CtlAlternativo:index" }
    methods:  GET

alternativo_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:CtlAlternativo:show" }
    methods:  GET

alternativo_new:
    path:     /new
    defaults: { _controller: "MaestroModeloBundle:CtlAlternativo:new" }
    methods:  [GET, POST]

alternativo_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaestroModeloBundle:CtlAlternativo:edit" }
    methods:  [GET, POST]

alternativo_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaestroModeloBundle:CtlAlternativo:delete" }
    methods:  DELETE
