canton_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:CtlCanton:index" }
    methods:  GET

canton_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:CtlCanton:show" }
    methods:  GET

canton_new:
    path:     /new
    defaults: { _controller: "MaestroModeloBundle:CtlCanton:new" }
    methods:  [GET, POST]

canton_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaestroModeloBundle:CtlCanton:edit" }
    methods:  [GET, POST]

canton_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaestroModeloBundle:CtlCanton:delete" }
    methods:  DELETE
