eco_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:CtlEquipo:index" }
    methods:  GET

eco_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:CtlEquipo:show" }
    methods:  GET

eco_new:
    path:     /new
    defaults: { _controller: "MaestroModeloBundle:CtlEquipo:new" }
    methods:  [GET, POST]

eco_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaestroModeloBundle:CtlEquipo:edit" }
    methods:  [GET, POST]

eco_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaestroModeloBundle:CtlEquipo:delete" }
    methods:  DELETE
