grupo_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:CtlGrupo:index" }
    methods:  GET

grupo_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:CtlGrupo:show" }
    methods:  GET

grupo_new:
    path:     /new
    defaults: { _controller: "MaestroModeloBundle:CtlGrupo:new" }
    methods:  [GET, POST]

grupo_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaestroModeloBundle:CtlGrupo:edit" }
    methods:  [GET, POST]

grupo_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaestroModeloBundle:CtlGrupo:delete" }
    methods:  DELETE
