log_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:CtlLog:index" }
    methods:  GET

log_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:CtlLog:show" }
    methods:  GET



