nivel_uso_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:CtlNivelUso:index" }
    methods:  GET

nivel_uso_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:CtlNivelUso:show" }
    methods:  GET

nivel_uso_new:
    path:     /new
    defaults: { _controller: "MaestroModeloBundle:CtlNivelUso:new" }
    methods:  [GET, POST]

nivel_uso_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaestroModeloBundle:CtlNivelUso:edit" }
    methods:  [GET, POST]

nivel_uso_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaestroModeloBundle:CtlNivelUso:delete" }
    methods:  DELETE
