principio_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:CtlPrincipio:index" }
    methods:  GET

principio_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:CtlPrincipio:show" }
    methods:  GET

principio_new:
    path:     /new
    defaults: { _controller: "MaestroModeloBundle:CtlPrincipio:new" }
    methods:  [GET, POST]

principio_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaestroModeloBundle:CtlPrincipio:edit" }
    methods:  [GET, POST]

principio_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaestroModeloBundle:CtlPrincipio:delete" }
    methods:  DELETE
