programa_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:CtlPrograma:index" }
    methods:  GET

programa_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:CtlPrograma:show" }
    methods:  GET

programa_new:
    path:     /new
    defaults: { _controller: "MaestroModeloBundle:CtlPrograma:new" }
    methods:  [GET, POST]

programa_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaestroModeloBundle:CtlPrograma:edit" }
    methods:  [GET, POST]

programa_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaestroModeloBundle:CtlPrograma:delete" }
    methods:  DELETE
