producto_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:CtlProducto:index" }
    methods:  GET

producto_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:CtlProducto:show" }
    methods:  GET

producto_new:
    path:     /new
    defaults: { _controller: "MaestroModeloBundle:CtlProducto:new" }
    methods:  [GET, POST]

producto_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaestroModeloBundle:CtlProducto:edit" }
    methods:  [GET, POST]

producto_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaestroModeloBundle:CtlProducto:delete" }
    methods:  DELETE
