presentacion_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:CtlPresentacion:index" }
    methods:  GET

presentacion_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:CtlPresentacion:show" }
    methods:  GET

presentacion_new:
    path:     /new
    defaults: { _controller: "MaestroModeloBundle:CtlPresentacion:new" }
    methods:  [GET, POST]

presentacion_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaestroModeloBundle:CtlPresentacion:edit" }
    methods:  [GET, POST]

presentacion_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaestroModeloBundle:CtlPresentacion:delete" }
    methods:  DELETE
