suministro_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:CtlSuministro:index" }
    methods:  GET

suministro_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:CtlSuministro:show" }
    methods:  GET

suministro_new:
    path:     /new
    defaults: { _controller: "MaestroModeloBundle:CtlSuministro:new" }
    methods:  [GET, POST]

suministro_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaestroModeloBundle:CtlSuministro:edit" }
    methods:  [GET, POST]

suministro_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaestroModeloBundle:CtlSuministro:delete" }
    methods:  DELETE
