servicio_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:CtlServicio:index" }
    methods:  GET

servicio_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:CtlServicio:show" }
    methods:  GET

servicio_new:
    path:     /new
    defaults: { _controller: "MaestroModeloBundle:CtlServicio:new" }
    methods:  [GET, POST]

servicio_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaestroModeloBundle:CtlServicio:edit" }
    methods:  [GET, POST]

servicio_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaestroModeloBundle:CtlServicio:delete" }
    methods:  DELETE
