unidad_medida_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:CtlUnidadMedida:index" }
    methods:  GET

unidad_medida_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:CtlUnidadMedida:show" }
    methods:  GET

unidad_medida_new:
    path:     /new
    defaults: { _controller: "MaestroModeloBundle:CtlUnidadMedida:new" }
    methods:  [GET, POST]

unidad_medida_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaestroModeloBundle:CtlUnidadMedida:edit" }
    methods:  [GET, POST]

unidad_medida_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaestroModeloBundle:CtlUnidadMedida:delete" }
    methods:  DELETE
