fosgrupo_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:FosGroup:index" }
    methods:  GET

fosgrupo_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:FosGroup:show" }
    methods:  GET

fosgrupo_new:
    path:     /new
    defaults: { _controller: "MaestroModeloBundle:FosGroup:new" }
    methods:  [GET, POST]

fosgrupo_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaestroModeloBundle:FosGroup:edit" }
    methods:  [GET, POST]

fosgrupo_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaestroModeloBundle:FosGroup:delete" }
    methods:  DELETE
