admin_users_index:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:FosUser:index" }
    methods:  GET

admin_users_show:
    path:     /{id}/show
    defaults: { _controller: "MaestroModeloBundle:FosUser:show" }
    methods:  GET

admin_users_new:
    path:     /new
    defaults: { _controller: "FOSUserBundle:Registration:register" }
    methods:  [GET, POST]

admin_users_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaestroModeloBundle:FosUser:edit" }
    methods:  [GET, POST]

admin_users_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaestroModeloBundle:FosUser:delete" }
    methods:  DELETE
