maestro_core_homepage:
    path:     /core
    defaults: { _controller: MaestroCoreBundle:Default:index }
maestro_core_ayuda:
    path:     /ayuda
    defaults: { _controller: MaestroCoreBundle:Default:ayuda }
maestro_core_schema:
    path:     /schema
    defaults: { _controller: MaestroCoreBundle:Default:schema }
maestro_core_feed:
    path:     /rss.xml
    defaults: { _controller: MaestroCoreBundle:Default:feed }
maestro_core_syslog:
    path:     /syslog
    defaults: { _controller: MaestroCoreBundle:Default:syslog }
