security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
#            pattern:    ^/
#            anonymous: ~
#            http_basic:
#            form_login:
#                check_path: /login_check
#                login_path: /login
#                
            logout: true
            security: true
            anonymous: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
#                default_target_path: /catalogo
#                always_use_default_target_path: true
            logout:       true
            anonymous:    true
    access_control:
#        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/ayuda*, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/*, role: IS_AUTHENTICATED_FULLY }
#        - { path: ^/register, role: ROLE_ADMIN }
#        - { path: ^/resetting, role: ROLE_ADMIN }
#        - { path: ^/admin/, role: ROLE_ADMIN }
