maestro_homepage:
    path:     /
    defaults: { _controller: "MaestroModeloBundle:CtlEstablecimiento:home" }
    methods:  GET
maestro_homepage_anonimo:
    path:     /catalogo
    defaults: { _controller: "MaestroModeloBundle:CtlEstablecimiento:home" }
    methods:  GET
maestro_modelo:
    resource: "@MaestroModeloBundle/Resources/config/routing.yml"
    prefix:   /
maestro_api:
    resource: "@MaestroApiBundle/Resources/config/routing.yml"
    prefix:   /
maestro_core:
    resource: "@MaestroCoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
