maestro_insumo:
    resource: "@MaestroInsumoBundle/Resources/config/routing.yml"
    prefix:   /

maestro_plantilla:
    resource: "@MaestroPlantillaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
