fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

minsal_suministro:
    resource: "@MinsalSuministroBundle/Resources/config/routing.yml"
    prefix:   /

minsal_core:
    resource: "@MinsalCoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
