security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
    access_control:
        # solo interno
        - { path: ^/insumos/json$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/rss.xml$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # Desabilitado registro solo para admin
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        # Autenticados
        - { path: ^/(.+), roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/ufi/especificogasto/, role: ROLE_UFI }
        # homepage
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
