grupos_index:
    path:     /
    defaults: { _controller: "MinsalSuministroBundle:CtlGrupo:index" }
    methods:  GET

grupos_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalSuministroBundle:CtlGrupo:show" }
    methods:  GET

grupos_new:
    path:     /new
    defaults: { _controller: "MinsalSuministroBundle:CtlGrupo:new" }
    methods:  [GET, POST]

grupos_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalSuministroBundle:CtlGrupo:edit" }
    methods:  [GET, POST]

grupos_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalSuministroBundle:CtlGrupo:delete" }
    methods:  DELETE
