niveluso_index:
    path:     /
    defaults: { _controller: "MinsalSuministroBundle:CtlNivelUso:index" }
    methods:  GET

niveluso_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalSuministroBundle:CtlNivelUso:show" }
    methods:  GET

niveluso_new:
    path:     /new
    defaults: { _controller: "MinsalSuministroBundle:CtlNivelUso:new" }
    methods:  [GET, POST]

niveluso_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalSuministroBundle:CtlNivelUso:edit" }
    methods:  [GET, POST]

niveluso_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalSuministroBundle:CtlNivelUso:delete" }
    methods:  DELETE
