presentaciones_index:
    path:     /
    defaults: { _controller: "MinsalSuministroBundle:CtlPresentacion:index" }
    methods:  GET

presentaciones_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalSuministroBundle:CtlPresentacion:show" }
    methods:  GET

presentaciones_new:
    path:     /new
    defaults: { _controller: "MinsalSuministroBundle:CtlPresentacion:new" }
    methods:  [GET, POST]

presentaciones_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalSuministroBundle:CtlPresentacion:edit" }
    methods:  [GET, POST]

presentaciones_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalSuministroBundle:CtlPresentacion:delete" }
    methods:  DELETE
