programas_index:
    path:     /
    defaults: { _controller: "MinsalSuministroBundle:CtlPrograma:index" }
    methods:  GET

programas_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalSuministroBundle:CtlPrograma:show" }
    methods:  GET

programas_new:
    path:     /new
    defaults: { _controller: "MinsalSuministroBundle:CtlPrograma:new" }
    methods:  [GET, POST]

programas_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalSuministroBundle:CtlPrograma:edit" }
    methods:  [GET, POST]

programas_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalSuministroBundle:CtlPrograma:delete" }
    methods:  DELETE
