suministros_index:
    path:     /
    defaults: { _controller: "MinsalSuministroBundle:CtlSuministro:index" }
    methods:  GET

suministros_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalSuministroBundle:CtlSuministro:show" }
    methods:  GET

suministros_new:
    path:     /new
    defaults: { _controller: "MinsalSuministroBundle:CtlSuministro:new" }
    methods:  [GET, POST]

suministros_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalSuministroBundle:CtlSuministro:edit" }
    methods:  [GET, POST]

suministros_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalSuministroBundle:CtlSuministro:delete" }
    methods:  DELETE
