productos_index:
    path:     /
    defaults: { _controller: "MinsalSuministroBundle:MntInsumo:index" }
    methods:  GET

productos_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalSuministroBundle:MntInsumo:show" }
    methods:  GET

productos_new:
    path:     /new
    defaults: { _controller: "MinsalSuministroBundle:MntInsumo:new" }
    methods:  [GET, POST]

productos_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalSuministroBundle:MntInsumo:edit" }
    methods:  [GET, POST]

productos_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalSuministroBundle:MntInsumo:delete" }
    methods:  DELETE
