maestro_modelo_establecimiento:
    resource: "@MaestroModeloBundle/Resources/config/routing/ctlestablecimiento.yml"
    prefix:   /establecimiento
maestro_modelo_canton:
    resource: "@MaestroModeloBundle/Resources/config/routing/ctlcanton.yml"
    prefix:   /canton

maestro_modelo_homepage:
    path:     /
    defaults: { _controller: MaestroModeloBundle:Default:index }
