maestro_modelo_admin_users:
    resource: "@MaestroModeloBundle/Resources/config/routing/fosuser.yml"
    prefix:   /admin/users
maestro_modelo_prestacion:
    resource: "@MaestroModeloBundle/Resources/config/routing/ctlprestacion.yml"
    prefix:   /prestacion
maestro_modelo_acceso:
    resource: "@MaestroModeloBundle/Resources/config/routing/ctlacceso.yml"
    prefix:   /admin/acceso
maestro_modelo_recurso:
    resource: "@MaestroModeloBundle/Resources/config/routing/ctlrecursohumano.yml"
    prefix:   /recurso
maestro_modelo_servicio:
    resource: "@MaestroModeloBundle/Resources/config/routing/ctlservicio.yml"
    prefix:   /servicio
maestro_modelo_situacionlegal:
    resource: "@MaestroModeloBundle/Resources/config/routing/ctlsituacionlegal.yml"
    prefix:   /situacionlegal
maestro_modelo_tipoestablecimiento:
    resource: "@MaestroModeloBundle/Resources/config/routing/ctltipoestablecimiento.yml"
    prefix:   /tipoestablecimiento
maestro_modelo_schema:
    resource: "@MaestroModeloBundle/Resources/config/routing/ctlschema.yml"
    prefix:   /schema
maestro_modelo_red:
    resource: "@MaestroModeloBundle/Resources/config/routing/ctlmicrored.yml"
    prefix:   /red
maestro_modelo_establecimiento:
    resource: "@MaestroModeloBundle/Resources/config/routing/ctlestablecimiento.yml"
    prefix:   /establecimiento
maestro_modelo_canton:
    resource: "@MaestroModeloBundle/Resources/config/routing/ctlcanton.yml"
    prefix:   /canton

maestro_modelo_homepage:
    path:     /
    defaults: { _controller: MaestroModeloBundle:Default:index }
