minsal_core_homepage:
    path:     /
    defaults: { _controller: MinsalCoreBundle:Default:index }
    
minsal_core_feed:
    path:     /rss.xml
    defaults: { _controller: MinsalCoreBundle:Default:feed }
